server:
  port: ${PORT:8080}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
management:
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true
    process.enabled: true
    git.enabled: true
    git.mode: full
  otlp:
    metrics:
      export:
        enabled: ${MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED:true}
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
        batchSize: ${OTEL_EXPORTER_OTLP_BATCH_SIZE:100}
        aggregationTemporality: ${OTEL_EXPORTER_OTLP_AGGREGATION_TEMPORALITY:cumulative}
        step: ${OTEL_EXPORTER_OTLP_AGGREGATION_STEP:1m}
        headers:
          Custom-Header: EHLO
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
      export:
        enabled: ${MANAGEMENT_OTLP_TRACING_EXPORT_ENABLED:true}
        headers:
          Custom-Header: EHLO
  endpoints:
    jmx.exposure.include: "*"
    web:
      exposure.include: "*"
      cors:
        allowed-origins: ${MANAGEMENT_CORS_ALLOWED_ORIGINS:*}
        allowed-methods: ${MANAGEMENT_CORS_ALLOWED_METHODS:*}
        max-age: ${MANAGEMENT_CORS_ALLOWED_MAXAGE:3600}
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
      show-components: always
    env:
      show-values: always
    configprops:
      show-values: always
  server:
    port: ${MANAGEMENT_PORT:8180}
spring:
  application:
    name: ${APP_NAME:spring-apigateway}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              filters:
                - PreserveHostHeader
                - StripPrefix=1
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${GATEWAY_CORS_ALLOWED_ORIGINS:'*'}
                allowedMethods: ${GATEWAY_CORS_ALLOWED_METHODS:'GET,POST,PUT,DELETE,HEAD,OPTIONS'}
                allowedHeaders: ${GATEWAY_CORS_ALLOWED_HEADERS:'Content-type,Authorization'}